### ISSUE TITLE
feat: 검색 페이지 작업

### ISSUE THREAD

**Issue by daun-up** [KMU-WINK/workinkorea-web#111]
## 어떤 기능인가요?

> 검색 페이지를 작업합니다.

## 작업 상세 내용

- [x] 검색창 구현
- [x] 실시간 트렌드 구현
- [x] 검색어 어떻게 전달?

**Comment by Choi-Jiwon-38** [comment]
@daun-up 
완료된 작업이어서 close 해두었어요~ 추가 작업 생기면 별도 이슈 생성하거나 reopen 해주세요!
